sudo: required
services:
  - docker

before_install:
  - docker build -t singhpa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true singhpa/react-test npm test

after_success:
  - docker build -t singhpa/multi-client ./client
  - docker build -t singhpa/multi-nginx ./nginx
  - docker build -t singhpa/multi-server ./server
  - docker build -t singhpa/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push singhpa/multi-client
  - docker push singhpa/multi-nginx
  - docker push singhpa/multi-server
  - docker push singhpa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-034313483791
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY